server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Sheldonccf/DIST_Student_Microservice
          search-paths:
            - employeeservice

          username: jdavid-araujo
          password: f@iry125
