#spring:
#  application:
#    name: test-service
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
#      password: ${CONFIG_SERVICE_PASSWORD}
#      username: user



data:
  env: NaN
  user:
    username: NaN
    password: NaN
